FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /src
COPY src/ ./src/

RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"

ENTRYPOINT ["sh", "-lc"]
CMD ["dotnet ef database update --project src/Freelaverse.Data --startup-project src/Freelaverse.API"]
